import type { Metadata } from 'next'
import { Expletus_Sans } from 'next/font/google'
import './globals.css'

const inter = Expletus_Sans({
  subsets: ['latin'],
   variable: '--font-expletus-sans ',
})

export const metadata: Metadata = {
  title: 'pic-fetch',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable} h-full`}>
      <body>{children}</body>
    </html>
  );
}
